# Generated by Django 5.2.2 on 2026-06-25 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("staffing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="手機號碼"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("customer", "客戶"), ("technician", "業務"), ("admin", "行政")],
                db_index=True,
                default="customer",
                max_length=20,
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="顯示名稱"),
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("city", models.CharField(blank=True, max_length=20, verbose_name="縣市")),
                ("dist", models.CharField(blank=True, max_length=20, verbose_name="行政區")),
                ("addr", models.CharField(blank=True, max_length=200, verbose_name="詳細地址")),
                (
                    "pkg_remaining",
                    models.PositiveIntegerField(default=0, verbose_name="套組剩餘次數"),
                ),
                ("pkg_total", models.PositiveIntegerField(default=0, verbose_name="套組總次數")),
                ("has_pets", models.BooleanField(default=False, verbose_name="家中有寵物")),
                ("has_baby", models.BooleanField(default=False, verbose_name="家中有嬰幼兒")),
                (
                    "allergy",
                    models.CharField(blank=True, max_length=200, verbose_name="過敏 / 特殊備註"),
                ),
                ("notify_push", models.BooleanField(default=True, verbose_name="推播通知")),
                ("notify_sms", models.BooleanField(default=True, verbose_name="簡訊通知")),
                ("onboarded", models.BooleanField(default=False, verbose_name="已完成新手引導")),
                ("manual", models.BooleanField(default=False, verbose_name="行政代建")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "客戶資料",
                "verbose_name_plural": "客戶資料",
            },
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1, default=5, max_digits=3, verbose_name="平均評分"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "在線"), ("banned", "禁牌中"), ("disabled", "停用")],
                        default="online",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "areas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="staff",
                        to="staffing.servicearea",
                        verbose_name="服務區",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "業務資料",
                "verbose_name_plural": "業務資料",
            },
        ),
    ]
