# Generated by Django 5.2.2 on 2026-06-25 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor", models.CharField(max_length=100, verbose_name="操作者")),
                ("action", models.CharField(max_length=100, verbose_name="動作")),
                ("target", models.CharField(blank=True, max_length=300, verbose_name="對象")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="時間"),
                ),
            ],
            options={
                "verbose_name": "操作歷程",
                "verbose_name_plural": "操作歷程",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[("demo", "免費體驗"), ("package", "套組服務"), ("ac", "冷氣清洗")],
                        max_length=20,
                        verbose_name="服務類型",
                    ),
                ),
                ("date", models.DateField(verbose_name="服務日期")),
                ("slot", models.CharField(max_length=20, verbose_name="時段")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("待派工", "待派工"),
                            ("已確認", "已確認"),
                            ("待出發", "待出發"),
                            ("進行中", "進行中"),
                            ("已完成", "已完成"),
                            ("已取消", "已取消"),
                            ("棄單", "棄單"),
                        ],
                        default="已確認",
                        max_length=10,
                        verbose_name="狀態",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=250, verbose_name="服務地址")),
                ("has_pets", models.BooleanField(default=False, verbose_name="家中有寵物")),
                ("has_baby", models.BooleanField(default=False, verbose_name="家中有嬰幼兒")),
                ("note", models.CharField(blank=True, max_length=300, verbose_name="備註")),
                ("ac_type", models.CharField(blank=True, max_length=20, verbose_name="冷氣類型")),
                ("units", models.PositiveIntegerField(default=0, verbose_name="台數")),
                ("price", models.PositiveIntegerField(default=0, verbose_name="試算費用")),
                ("auto_assigned", models.BooleanField(default=True, verbose_name="自動派工")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "預約",
                "verbose_name_plural": "預約",
                "ordering": ["-date", "slot"],
            },
        ),
        migrations.CreateModel(
            name="Compensation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(max_length=200, verbose_name="原因")),
                ("redeemed", models.BooleanField(default=False, verbose_name="已使用")),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compensations",
                        to="bookings.booking",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "補償服務",
                "verbose_name_plural": "補償服務",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Completion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=1, default=1.5, max_digits=4, verbose_name="服務時數"
                    ),
                ),
                ("items", models.JSONField(blank=True, default=dict, verbose_name="服務項目明細")),
                (
                    "cust_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="服務備註（客戶可見）"
                    ),
                ),
                (
                    "internal_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="內部記錄（客戶看不到）"
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(default=0, verbose_name="客戶評分")),
                ("comment", models.CharField(blank=True, max_length=300, verbose_name="客戶留言")),
                ("fee", models.PositiveIntegerField(default=0, verbose_name="車馬費")),
                (
                    "fee_status",
                    models.CharField(
                        choices=[("-", "無"), ("待匯出", "待匯出"), ("已匯出", "已匯出")],
                        default="-",
                        max_length=10,
                        verbose_name="計酬狀態",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        db_index=True, max_length=7, verbose_name="所屬月份（YYYY-MM）"
                    ),
                ),
                ("signed", models.BooleanField(default=False, verbose_name="客戶已簽名")),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "完工紀錄",
                "verbose_name_plural": "完工紀錄",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["customer", "status"], name="bookings_bo_custome_0cbf77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["staff", "date"], name="bookings_bo_staff_i_9b9c87_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["date"], name="bookings_bo_date_e2d163_idx"),
        ),
    ]
