# Generated by Django 5.2.2 on 2026-06-25 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("city", models.CharField(max_length=20, verbose_name="縣市")),
                ("district", models.CharField(max_length=20, verbose_name="行政區")),
            ],
            options={
                "verbose_name": "服務區",
                "verbose_name_plural": "服務區",
                "ordering": ["city", "district"],
                "constraints": [
                    models.UniqueConstraint(fields=("city", "district"), name="uniq_service_area")
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.CharField(max_length=7, verbose_name="月份（YYYY-MM）")),
                ("slots", models.JSONField(blank=True, default=dict, verbose_name="開放時段")),
                ("submitted", models.BooleanField(default=False, verbose_name="已提交")),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "業務班表",
                "verbose_name_plural": "業務班表",
                "ordering": ["-month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "month"), name="uniq_staff_month_schedule"
                    )
                ],
            },
        ),
    ]
