# Generated by Django 5.2.2 on 2026-06-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PayrollSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "travel_fee",
                    models.PositiveIntegerField(default=400, verbose_name="車馬費（每場完工 NT$）"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新時間")),
            ],
            options={
                "verbose_name": "薪資參數",
                "verbose_name_plural": "薪資參數",
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="名稱")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("amount", "折抵金額"),
                            ("percent", "折抵百分比"),
                            ("bonus", "加贈次數"),
                            ("free_trial", "免費試用"),
                        ],
                        max_length=20,
                        verbose_name="優惠類型",
                    ),
                ),
                ("value", models.IntegerField(default=0, verbose_name="優惠值")),
                ("active", models.BooleanField(default=True, verbose_name="啟用")),
            ],
            options={
                "verbose_name": "優惠活動",
                "verbose_name_plural": "優惠活動",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="名稱")),
                ("desc", models.CharField(blank=True, max_length=200, verbose_name="描述")),
                ("price", models.PositiveIntegerField(default=0, verbose_name="單價（NT$）")),
                (
                    "duration",
                    models.PositiveIntegerField(default=60, verbose_name="預設時長（分鐘）"),
                ),
                ("is_base", models.BooleanField(default=False, verbose_name="基礎 SKU")),
                ("is_addon", models.BooleanField(default=False, verbose_name="加購項目")),
                ("active", models.BooleanField(default=True, verbose_name="啟用")),
            ],
            options={
                "verbose_name": "服務項目",
                "verbose_name_plural": "服務項目",
                "ordering": ["-is_base", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServicePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="名稱")),
                ("total", models.PositiveIntegerField(default=8, verbose_name="總次數")),
                ("price", models.PositiveIntegerField(default=0, verbose_name="售價（NT$）")),
                ("active", models.BooleanField(default=True, verbose_name="啟用")),
            ],
            options={
                "verbose_name": "套組方案",
                "verbose_name_plural": "套組方案",
                "ordering": ["price"],
            },
        ),
    ]
